---
allowed_users:
  6784285433:
    label: 'Demi'
    permissions:
      can_manage_backups: True
      can_manage_users: False
  7233636327:
    label: 'Mia Madre'
    permissions:
      can_manage_backups: True
      can_manage_users: False